type Source = { filename: string; page?: number; snippet?: string };

type ExportInput = {
  workspaceName: string;
  dealCode?: string | null;
  threadTitle?: string | null;
  question?: string;
  answer: string;
  createdAt: Date;
  confidence?: number | null;
  authorLabel: string; // e.g. "IC Bot" or "Deal team"
  sources?: Source[];
};

/**
 * Canonical text representation of a Q&A for pasting into an IC memo.
 * Used by the Copy button and the print view (rendered as markdown there).
 */
export function formatForExport(input: ExportInput): string {
  const lines: string[] = [];
  const dateStr = input.createdAt.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric"
  });
  const dealHeader = input.dealCode
    ? `${input.workspaceName} (${input.dealCode})`
    : input.workspaceName;

  lines.push(`# ${dealHeader} — IC Bot Q&A`);
  lines.push(`_${dateStr}${input.threadTitle ? ` · ${input.threadTitle}` : ""}_`);
  lines.push("");

  if (input.question) {
    lines.push(`## Question`);
    lines.push(input.question);
    lines.push("");
  }

  lines.push(`## Answer`);
  if (typeof input.confidence === "number" && input.authorLabel === "IC Bot") {
    lines.push(`_Answered by IC Bot · confidence ${(input.confidence * 100).toFixed(0)}%_`);
    lines.push("");
  } else {
    lines.push(`_Answered by ${input.authorLabel}_`);
    lines.push("");
  }
  lines.push(input.answer.trim());
  lines.push("");

  if (input.sources && input.sources.length > 0) {
    lines.push(`## Sources`);
    for (const s of input.sources) {
      lines.push(`- ${s.filename}${s.page ? `, page ${s.page}` : ""}`);
    }
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`Generated by the LKCM IC Bot. Internal use only.`);
  return lines.join("\n");
}
