-- Enable pgvector. Must run before any CREATE TABLE that references `vector`.
CREATE EXTENSION IF NOT EXISTS vector;

-- The rest of the schema is generated by `prisma migrate dev` after this file runs.
-- This migration exists so the extension is present for the first generated migration.
