import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { requireWorkspaceAccess } from "@/lib/access";
import { formatDateTime } from "@/lib/utils";
import { Markdown } from "@/components/markdown";
import { Wordmark } from "@/components/wordmark";
import { PrintTriggers } from "./print-triggers";

type Source = { filename: string; page?: number };

export default async function ExportMessagePage({
  params
}: {
  params: Promise<{ id: string; messageId: string }>;
}) {
  const { id: workspaceId, messageId } = await params;
  await requireWorkspaceAccess(workspaceId);

  const message = await prisma.message.findFirst({
    where: { id: messageId, thread: { workspaceId } },
    include: {
      thread: {
        include: {
          workspace: { select: { name: true, dealCode: true } },
          messages: {
            where: { role: "user" },
            orderBy: { createdAt: "desc" },
            take: 1
          }
        }
      },
      createdBy: { select: { name: true, email: true } }
    }
  });

  if (!message || message.role === "user") notFound();

  const question = message.thread.messages[0]?.content ?? "(question unavailable)";
  const sources =
    ((message.citationsJson as { sources?: Source[] } | null)?.sources ?? []) as Source[];

  const authorLabel =
    message.role === "dealteam"
      ? `Deal team${message.createdBy?.name ? ` — ${message.createdBy.name}` : ""}`
      : "IC Bot";

  const dealHeader = message.thread.workspace.dealCode
    ? `${message.thread.workspace.name} · ${message.thread.workspace.dealCode}`
    : message.thread.workspace.name;

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white; }
          .print-page { box-shadow: none !important; border: none !important; padding: 0 !important; }
        }
        @page { margin: 0.75in; }
      `}</style>
      <div className="mx-auto my-8 max-w-3xl px-6">
        <PrintTriggers />
        <div className="print-page rounded-lg border border-slate-200 bg-white p-10 shadow-sm">
          <header className="mb-6 flex items-start justify-between border-b border-slate-200 pb-4">
            <div>
              <div className="text-xs font-semibold uppercase tracking-widest text-slate-500">
                Investment Committee
              </div>
              <h1 className="mt-1 text-xl font-semibold text-slate-900">{dealHeader}</h1>
              <div className="mt-1 text-xs text-slate-500">
                {message.thread.title ? `${message.thread.title} · ` : ""}
                {formatDateTime(message.createdAt)}
              </div>
            </div>
            <div className="shrink-0">
              <Wordmark variant="full" />
            </div>
          </header>

          <section className="mb-6">
            <div className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Question
            </div>
            <div className="mt-1 whitespace-pre-wrap rounded-md border border-slate-200 bg-slate-50 p-3 text-sm text-slate-900">
              {question}
            </div>
          </section>

          <section className="mb-6">
            <div className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Answer · {authorLabel}
              {message.role === "assistant" && message.confidence !== null ? (
                <span className="ml-2 text-slate-400">
                  confidence {(message.confidence! * 100).toFixed(0)}%
                </span>
              ) : null}
            </div>
            <div className="mt-1 rounded-md border border-slate-200 p-3">
              <Markdown>{message.content}</Markdown>
            </div>
          </section>

          {sources.length > 0 ? (
            <section className="mb-6">
              <div className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                Sources
              </div>
              <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-slate-700">
                {sources.map((s, i) => (
                  <li key={i}>
                    <span className="font-medium">{s.filename}</span>
                    {s.page ? `, page ${s.page}` : ""}
                  </li>
                ))}
              </ul>
            </section>
          ) : null}

          <footer className="mt-10 border-t border-slate-200 pt-4 text-xs text-slate-500">
            Generated by the LKCM Headwater IC Bot. Internal use only.
          </footer>
        </div>
      </div>
    </>
  );
}
